// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.User;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace webapi.Migrations
{
  [DbContext(typeof(UserDbContext))]
  [Migration("20250710040707_CreateUserTable")]
  partial class CreateUserTable
  {
	/// <inheritdoc />
	protected override void BuildTargetModel(ModelBuilder modelBuilder)
	{
#pragma warning disable 612, 618
	  modelBuilder
		  .HasAnnotation("ProductVersion", "9.0.7")
		  .HasAnnotation("Relational:MaxIdentifierLength", 63);

	  NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

	  modelBuilder.Entity("Module.User.Entities.User", b =>
		  {
			b.Property<Guid>("Id")
					  .ValueGeneratedOnAdd()
					  .HasColumnType("uuid");

			b.Property<string>("Address")
					  .HasColumnType("text");

			b.Property<DateTime>("CreatedAt")
					  .HasColumnType("timestamp with time zone");

			b.Property<DateTime?>("DeletedAt")
					  .HasColumnType("timestamp with time zone");

			b.Property<DateTime?>("Dob")
					  .HasColumnType("timestamp with time zone");

			b.Property<string>("Email")
					  .IsRequired()
					  .HasColumnType("text");

			b.Property<string>("Name")
					  .IsRequired()
					  .HasColumnType("text");

			b.Property<string>("Password")
					  .IsRequired()
					  .HasColumnType("text");

			b.Property<string>("Role")
					  .HasColumnType("text");

			b.Property<DateTime?>("UpdatedAt")
					  .HasColumnType("timestamp with time zone");

			b.HasKey("Id");

			b.ToTable("user");
		  });
#pragma warning restore 612, 618
	}
  }
}
