@webapi_HostAddress = http://localhost:5266

### GET /weatherforecast
GET {{webapi_HostAddress}}/api/user

### POST /weatherforecast
POST {{webapi_HostAddress}}/api/user

{
	"name": "haquocdat",
	"email": "haquocdat@gmail.com",
	"password": "12345678"
}

