@webapi_HostAddress = http://localhost:5266

### GET /api/user
GET {{webapi_HostAddress}}/api/user

### POST /api/user
POST {{webapi_HostAddress}}/api/user

{
	"name": "haquocdat",
	"email": "haquocdat@gmail.com",
	"password": "12345678"
}

### POST /api/user/login
POST {{webapi_HostAddress}}/api/user/login

{
	"name": "haquocdat",
	"password": "12345678"
}

