@webapi_HostAddress = http://localhost:5266
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJoYXF1b2NkYXQiLCJqdGkiOiJlMTVjZmIyYS01ODUyLTQwZjYtYmZhNi03ODg3MDY3MTU0ZGQiLCJleHAiOjE3NTQxMTM2MjMsImlzcyI6IllvdXJBcHAiLCJhdWQiOiJZb3VyQXBwVXNlcnMifQ.T6ldAhafBsLPZDV5iSwibtXk0foPcx65nMQe4lzOMdo

### GET /api/user
GET {{webapi_HostAddress}}/api/user

### POST /api/user
POST {{webapi_HostAddress}}/api/user

{
	"name": "haquocdat",
	"email": "haquocdat@gmail.com",
	"password": "12345678"
}

### POST /api/user/seed
POST {{webapi_HostAddress}}/api/user/seed

### POST /api/user/login
POST {{webapi_HostAddress}}/api/user/login

{
	"name": "haquocdat",
	"password": "12345678"
}

### PATCH /api/user/password
PATCH {{webapi_HostAddress}}/api/user/password

{
	"name": "haquocdat",
	"password": "12345678",
	"newpassword": "12345679"
}

### PATCH /api/user/password
PATCH {{webapi_HostAddress}}/api/user/password

{
	"name": "haquocdat",
	"password": "12345679",
	"newpassword": "12345678"
}

### DELETE /api/user
DELETE {{webapi_HostAddress}}/api/user
Content-Type: application/json
Authorization: {{TOKEN}}

{
	"name": "haquocdat",
	"password": "12345678"
}

